apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: guestbook-ui
  annotations: guestbook_version1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: hekai/gcr.io_heptio-images_ks-guestbook-demo_0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
